
package br.gov.camara.sitcamaraws.sessoesreunioes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessoesReunioes", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", wsdlLocation = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes.asmx?wsdl")
public class SessoesReunioes
    extends Service
{

    private final static URL SESSOESREUNIOES_WSDL_LOCATION;
    private final static WebServiceException SESSOESREUNIOES_EXCEPTION;
    private final static QName SESSOESREUNIOES_QNAME = new QName("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", "SessoesReunioes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSOESREUNIOES_WSDL_LOCATION = url;
        SESSOESREUNIOES_EXCEPTION = e;
    }

    public SessoesReunioes() {
        super(__getWsdlLocation(), SESSOESREUNIOES_QNAME);
    }

    public SessoesReunioes(WebServiceFeature... features) {
        super(__getWsdlLocation(), SESSOESREUNIOES_QNAME, features);
    }

    public SessoesReunioes(URL wsdlLocation) {
        super(wsdlLocation, SESSOESREUNIOES_QNAME);
    }

    public SessoesReunioes(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SESSOESREUNIOES_QNAME, features);
    }

    public SessoesReunioes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessoesReunioes(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SessoesReunioesSoap
     */
    @WebEndpoint(name = "SessoesReunioesSoap")
    public SessoesReunioesSoap getSessoesReunioesSoap() {
        return super.getPort(new QName("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", "SessoesReunioesSoap"), SessoesReunioesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessoesReunioesSoap
     */
    @WebEndpoint(name = "SessoesReunioesSoap")
    public SessoesReunioesSoap getSessoesReunioesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", "SessoesReunioesSoap"), SessoesReunioesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSOESREUNIOES_EXCEPTION!= null) {
            throw SESSOESREUNIOES_EXCEPTION;
        }
        return SESSOESREUNIOES_WSDL_LOCATION;
    }

}
