
package br.gov.camara.sitcamaraws.sessoesreunioes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SessoesReunioesSoap", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SessoesReunioesSoap {


    /**
     * 
     * @return
     *     returns br.gov.camara.sitcamaraws.sessoesreunioes.ListarSituacoesReuniaoSessaoResponse.ListarSituacoesReuniaoSessaoResult
     */
    @WebMethod(operationName = "ListarSituacoesReuniaoSessao", action = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarSituacoesReuniaoSessao")
    @WebResult(name = "ListarSituacoesReuniaoSessaoResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
    @RequestWrapper(localName = "ListarSituacoesReuniaoSessao", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarSituacoesReuniaoSessao")
    @ResponseWrapper(localName = "ListarSituacoesReuniaoSessaoResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarSituacoesReuniaoSessaoResponse")
    public br.gov.camara.sitcamaraws.sessoesreunioes.ListarSituacoesReuniaoSessaoResponse.ListarSituacoesReuniaoSessaoResult listarSituacoesReuniaoSessao();

    /**
     * 
     * @param dataIni
     * @param dataFim
     * @param numMatriculaParlamentar
     * @return
     *     returns br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasParlamentarResponse.ListarPresencasParlamentarResult
     */
    @WebMethod(operationName = "ListarPresencasParlamentar", action = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarPresencasParlamentar")
    @WebResult(name = "ListarPresencasParlamentarResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
    @RequestWrapper(localName = "ListarPresencasParlamentar", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasParlamentar")
    @ResponseWrapper(localName = "ListarPresencasParlamentarResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasParlamentarResponse")
    public br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasParlamentarResponse.ListarPresencasParlamentarResult listarPresencasParlamentar(
        @WebParam(name = "dataIni", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String dataIni,
        @WebParam(name = "dataFim", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String dataFim,
        @WebParam(name = "numMatriculaParlamentar", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String numMatriculaParlamentar);

    /**
     * 
     * @param codigoSessao
     * @param dataIni
     * @param dataFim
     * @param parteNomeParlamentar
     * @param siglaPartido
     * @param siglaUF
     * @return
     *     returns br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosPlenarioResponse.ListarDiscursosPlenarioResult
     */
    @WebMethod(operationName = "ListarDiscursosPlenario", action = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarDiscursosPlenario")
    @WebResult(name = "ListarDiscursosPlenarioResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
    @RequestWrapper(localName = "ListarDiscursosPlenario", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosPlenario")
    @ResponseWrapper(localName = "ListarDiscursosPlenarioResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosPlenarioResponse")
    public br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosPlenarioResponse.ListarDiscursosPlenarioResult listarDiscursosPlenario(
        @WebParam(name = "dataIni", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String dataIni,
        @WebParam(name = "dataFim", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String dataFim,
        @WebParam(name = "codigoSessao", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String codigoSessao,
        @WebParam(name = "parteNomeParlamentar", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String parteNomeParlamentar,
        @WebParam(name = "siglaPartido", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String siglaPartido,
        @WebParam(name = "siglaUF", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String siglaUF);

    /**
     * 
     * @param numQuarto
     * @param numOrador
     * @param codSessao
     * @param numInsercao
     * @return
     *     returns br.gov.camara.sitcamaraws.sessoesreunioes.ObterInteiroTeorDiscursosPlenarioResponse.ObterInteiroTeorDiscursosPlenarioResult
     */
    @WebMethod(action = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/obterInteiroTeorDiscursosPlenario")
    @WebResult(name = "obterInteiroTeorDiscursosPlenarioResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
    @RequestWrapper(localName = "obterInteiroTeorDiscursosPlenario", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ObterInteiroTeorDiscursosPlenario")
    @ResponseWrapper(localName = "obterInteiroTeorDiscursosPlenarioResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ObterInteiroTeorDiscursosPlenarioResponse")
    public br.gov.camara.sitcamaraws.sessoesreunioes.ObterInteiroTeorDiscursosPlenarioResponse.ObterInteiroTeorDiscursosPlenarioResult obterInteiroTeorDiscursosPlenario(
        @WebParam(name = "codSessao", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String codSessao,
        @WebParam(name = "numOrador", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String numOrador,
        @WebParam(name = "numQuarto", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String numQuarto,
        @WebParam(name = "numInsercao", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String numInsercao);

    /**
     * 
     * @param numMatriculaParlamentar
     * @param siglaPartido
     * @param data
     * @param siglaUF
     * @return
     *     returns br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasDiaResponse.ListarPresencasDiaResult
     */
    @WebMethod(operationName = "ListarPresencasDia", action = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/ListarPresencasDia")
    @WebResult(name = "ListarPresencasDiaResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
    @RequestWrapper(localName = "ListarPresencasDia", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasDia")
    @ResponseWrapper(localName = "ListarPresencasDiaResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasDiaResponse")
    public br.gov.camara.sitcamaraws.sessoesreunioes.ListarPresencasDiaResponse.ListarPresencasDiaResult listarPresencasDia(
        @WebParam(name = "data", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String data,
        @WebParam(name = "numMatriculaParlamentar", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String numMatriculaParlamentar,
        @WebParam(name = "siglaPartido", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String siglaPartido,
        @WebParam(name = "siglaUF", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String siglaUF);

    /**
     * 
     * @param datafim
     * @param dataini
     * @return
     *     returns br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosSessoesCongressoEncerradasResponse.ListarDiscursosSessoesCongressoEncerradasResult
     */
    @WebMethod(action = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes/listarDiscursosSessoesCongressoEncerradas")
    @WebResult(name = "listarDiscursosSessoesCongressoEncerradasResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
    @RequestWrapper(localName = "listarDiscursosSessoesCongressoEncerradas", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosSessoesCongressoEncerradas")
    @ResponseWrapper(localName = "listarDiscursosSessoesCongressoEncerradasResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes", className = "br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosSessoesCongressoEncerradasResponse")
    public br.gov.camara.sitcamaraws.sessoesreunioes.ListarDiscursosSessoesCongressoEncerradasResponse.ListarDiscursosSessoesCongressoEncerradasResult listarDiscursosSessoesCongressoEncerradas(
        @WebParam(name = "dataini", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String dataini,
        @WebParam(name = "datafim", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/SessoesReunioes")
        String datafim);

}
